name: Google Cloud Secrets Manager workflow

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - "main"
  #     - "18-end"
  #     - "master"

jobs:
  # test:
  #   runs-on: ubuntu-latest
  #     # strategy:
  #     # matrix:
  #     #   python-version: ["3.8","3.9","3.10"]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Setup Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.8"
  #     - name: Install requirements
  #       run: |
  #         python -m pip install -r src/requirements.txt
  #     - name: Run tests
  #       env:
  #         MODE: "github actions"
  #       run: |
  #         pytest src/tests.py


  update_secret:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{secrets.GOOGLE_CREDENTIALS}}'
      - name: Configure dotenv file
        run: |
          cat << EOF > .env
          MODE =${{ secrets.APP_MODE }}
          EOF
      - name: Run a new version of secrets
        run: |
          gcloud secrets versions add ${{secrets.GCLOUD_SECRET_LABEL}} --data-file .env
